### ISSUE TITLE
Revolution Slider Conflict

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#396]
When the slider revolution plugin is enabled, the Divi Builder does not save successfully when the save button is clicked. Also reports that revslider shortcodes are stripped from the page.

https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=589018

**Comment by lots0logs** [comment]
Also a report that Code Module containing Rev Slider shortcode gets lost completely when saving the page using the FB. The entire module has to be re-added and saved via the BB. 

https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=589156

**Comment by SlavaET** [comment]
Do we have a copy of this plugin for testing?

**Comment by SlavaET** [comment]
stripping the shortcode from Code module should be fixed in this PR - https://github.com/elegantthemes/submodule-builder/pull/1138
As for the Save button issue - I need a plugin to check it.

**Comment by websbyjd** [comment]
Here, I have the plugin
[revslider.zip](https://github.com/elegantthemes/Divi-Beta/files/461670/revslider.zip)

**Comment by timayhelen** [comment]
@SlavaET @uportnykh We still need to figure out why the page fails to save when Slider Revolution is installed. There are lot of complaints about the VB not saving, and this might just be one example of a larger problem. It's still happening in 3.0.2.

**Comment by timayhelen** [comment]
More discussion about failed saving here: https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=589018
