### ISSUE TITLE
Divi : Theme options : Grab the first post image not working

### ISSUE THREAD

**Issue by rijendra** [elegantthemes/Divi-Beta#582]
### Problem:

Grab the first post image options in the theme options is not working, tested on a post and archive pages, if the post doesn't have featured image then this option should show instead of featured image the first image but its not showing neither in single post or in archive.
### Steps To Reproduce:
1.  Enable Grab the first post image in theme options
2. Create a post with no featured image and an normal image in content area
3. View the post in archive and single post, they dont show up though display thumb option is enabled in theme options > layout settings.

**Comment by uportnykh** [comment]
@rijendra It seems to work ok for me. Can you still replicate the issue?

**Comment by rijendra** [comment]
Hi
Sorry i can still replicate the issue, this doesn't work for me when i use normal visual editor of default wordpress, no page builder on it.
It also doesn't work when using the page builder with image module and blurb module etc.

This only works with image in the text module content of page builder.
Thanks

**Comment by uportnykh** [comment]
@lots0logs Can you try to replicate it?

**Comment by lots0logs** [comment]
@uportnykh Yeah, it looks like the issue only occurs when the builder has been used for the post.

**Comment by SlavaET** [comment]
Fixed. 
**Note**: the fix is in the `submodule-epanel`

**Comment by lots0logs** [comment]
@SlavaET The fix works :+1:  However, I'm seeing the following notice in the debug log when on this branch:
```
[25-Oct-2016 18:13:35 UTC] PHP Notice:  Array to string conversion in /srv/et.falgout.us/wp-includes/shortcodes.php on line 326
```

**Comment by SlavaET** [comment]
@lots0logs fixed. There is additional PR for submodule-builder to fix that issue - https://github.com/elegantthemes/submodule-builder/issues/1346

**Comment by lots0logs** [comment]
@SlavaET 
![unnamed](https://cloud.githubusercontent.com/assets/4675662/19738433/00ff4302-9b7d-11e6-86ee-ca64b5a673dc.png)
use the same name for both branches?!? :wink:

**Comment by lots0logs** [comment]
@SlavaET Hmm..now the original issue is back (no image is shown for posts built with the Divi Builder).

**Comment by SlavaET** [comment]
@lots0logs sorry about branch names :)
It still works for me, the 2nd fix affects only Blog module, so it shouldn't break the original fix..
Can you please check again and make sure your ePanel is on the correct branch?
if you still see the issue - please share the layout you're using for your test post.

**Comment by lots0logs** [comment]
@SlavaET I think I might have been on the wrong branch (sorry). It is working BUT the notices are still showing up in the debug log:
```
[28-Oct-2016 19:43:48 UTC] PHP Notice:  Array to string conversion in /srv/et.falgout.us/wp-includes/shortcodes.php on line 326
[28-Oct-2016 19:43:48 UTC] PHP Notice:  Array to string conversion in /srv/et.falgout.us/wp-includes/shortcodes.php on line 326
[28-Oct-2016 19:43:49 UTC] PHP Notice:  Array to string conversion in /srv/et.falgout.us/wp-includes/shortcodes.php on line 326
[28-Oct-2016 19:43:50 UTC] PHP Notice:  Array to string conversion in /srv/et.falgout.us/wp-includes/shortcodes.php on line 326
```

I'm using the Homepage Extended Layout and adding a Blog Module below the blurbs (using the VB). I set the blog module to a category that includes a few posts which dont have featured images but do have images in the content.

**Comment by SlavaET** [comment]
@lots0logs I cannot reproduce it. I see the error when `submodule-builder` is on master, but error doesn't appear once I switch it to https://github.com/elegantthemes/submodule-builder/pull/1346
Which modules do you use in your posts which appear in Blog?

**Comment by lots0logs** [comment]
@SlavaET [This](http://et.falgout.us/divi/category/caption-test/) is the category I'm using. The first two posts are builder layouts. Let me know if you need access to the site.

**Comment by SlavaET** [comment]
@lots0logs I cannot reproduce the issue even with similar layouts as on your website. It would be great if you can provide me the WP and FTP details, so I can check what's wrong there.. Just ping me in Slack.

**Comment by lots0logs** [comment]
Just checked this again and its not outputting the log messages anymore :sweat_smile:
