### ISSUE TITLE
VB :: Post Slider :: Show Image On Mobile 

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#762]
### Problem:

Image is visible initially

![animation](https://cloud.githubusercontent.com/assets/9657712/20310887/d1895d50-ab77-11e6-9048-2de9d14c4fa3.gif)

Same in Divi Bulder plugin

**Comment by SlavaET** [comment]
Fixed.
Also, I found another issue. Top/Bottom image placement was not working correctly in the Post Slider, so I adjusted mechanism which calculates the slider height + adjusted some css to fix the alignment issues.

**Comment by lots0logs** [comment]
@SlavaET There are some issues with the positioning of the slide content. You can see them [here](http://et.falgout.us/divi/762-fix-post-slider-image-issues/).

**Comment by SlavaET** [comment]
@lots0logs please check the latest version of PR.

**Comment by lots0logs** [comment]
@SlavaET Its improved but there is still an issue with positioning (see screenshot). Also I'm only just now noticing that the URL is shown for OEmbed videos at the beginning of the content and the entire shortcode is shown for HTML5 videos. That was fixed recently in the blog module. Let's fix it here as well.  

![2016-11-17_04-35-38-pm](https://cloud.githubusercontent.com/assets/4675662/20496636/a3a5a60a-afeb-11e6-93bc-b000ec294076.png)

**Comment by SlavaET** [comment]
@lots0logs fixed the alignment issues. Please check it now.
As for the video, can you please explain how it was fixed in Blog? This is what I see on my end when `show excerpt` option enabled:
![image](https://cloud.githubusercontent.com/assets/3446682/20587626/586207ce-b239-11e6-9828-744fefd7cbd5.png)

If I enable `show content` option, then I can see the video correctly in both Blog and Post Slider module..

**Comment by lots0logs** [comment]
@SlavaET I can't recall exactly, I will try to find the issue for it though. In anycase, shortcodes should never be printed in excerpts. Let's do what is needed to ensure that is the case.

**Comment by SlavaET** [comment]
@lots0logs maybe we should do that in scope of a different issue? It's unrelated to the initial issue I fixed and it affects all the Post-based modules not only the Post Slider.
