### ISSUE TITLE
Code Module :: Output is messed up

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#769]
### Problem:

Not sure if this will be able to be replicate on your end. In a code module I did use this html code:
```
<div class="box">
	
	<div class="box-inner">
		
		<h2 class="box-title">Box Title</h2>

		<p>This is the box description</p>

	</div>
	
</div>
```

On a server running php 7.0.12 the output is as expected. On a server running php 5.4 and 5.6 the output is messed out:

<img width="960" alt="screen shot 2016-11-17 at 12 10 05 am" src="https://cloud.githubusercontent.com/assets/1719735/20367914/3a60b50c-ac5a-11e6-8e03-476c0f9bc100.png">

The strange part is that when using the Visual Builder the HTMl output is good, the problem only appear when using the Back End Builder.

Here is a video I did recorded from a server running php 7.0.12 and also from a server using php 5.6

https://drive.google.com/file/d/0B8PjD3Z_XQvuTjRjd1lsUE9felE/view?usp=sharing

The first part is from the server using php 7.0.12 while the second part is from a live server.

Hope it helps,
Kind Regards

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1498

**Comment by SlavaET** [comment]
@eduard-ungureanu I cannot reproduce the issue on php 5.6.2. Are you sure it's related to php version? Can you reproduce this issue on any other website?
Can you please import and share the layout of page after saving on your php 5.6 server? I'll take a look.

**Comment by eduard-ungureanu** [comment]
@SlavaET  sorry for delay, yes I Can reproduce the issue on php 5.6 (I'm afraid that's on local host) so I cannot give you access to it, I'm using MAMP and I can select the php version I want to use for a host.

**Comment by lots0logs** [comment]
@SlavaET I'm sending you the login details from @eduard-ungureanu comment on Slack now...I think he forgot that this is a public repo :smile:

**Comment by SlavaET** [comment]
Turned out this issue related to the mode of editor when you saving the content. If it set to `Text` mode, then extra `<p>` tags will be added when you hit `Update` in WP admin.
I was able to reproduce it locally. Looking for a solution.

**Comment by SlavaET** [comment]
Found a fix.
In my PR divi builder will remove the default `wputop` filter from the content and then apply it inside the modules except for Structure element ( like Sections, Rows, Columns ) and Code module.
Basically all the content inside Divi Builder will still be processed with `wpautop` function except for the content of Code module, so the content of Code module won't be modified.
I have one concern though, all the content which will be added to the page outside the Divi Builder modules won't be processed by `wpautop`, so it may potentially affect the output of some 3rd party plugins on the pages with Divi Builder which rely on default `wpautop`.

Another solution which won't affect the default content filtering is to remove all the line-breaks from the content of Code modules. In that case `wpautop` won't be applied to its content and no extra tags will be added, but we'll always remove all the line-breaks from code modules.

**Comment by SlavaET** [comment]
Clear steps to reproduce the original issue:
1) Switch the WP editor to Text mode ( just open Text module in Divi Builder and switch it to Text mode );
2) Add the code module with the content which contains line-breaks ( like the Eduard's code );
3) Check the output on front-end. Notice that line-breaks replaced with `<br>` multiple line-breaks replaced with `<p></p>`.

**Comment by lots0logs** [comment]
@SlavaET I think it would actually be okay to remove line breaks from the code module. The code module is intended for code, not text (obviously). Plus I really don't like the possibility of causing issues with content that isn't ours (the Divi Builders).

**Comment by timayhelen** [comment]
@SlavaET @lots0logs I don't think we want to strip lined breaks that are added to Code Modules on purpose though. We need to just leave the content in code modules alone somehow.

**Comment by lots0logs** [comment]
@timayhelen Just to be clear, we're talking about the line break character (`/n` on OSX & Linux and `/n/r` on Windows), not the HTML `<br>` tag.

**Comment by timayhelen** [comment]
@SlavaET I think we can strip out line break characters in the code module as long as purposeful line breaks added as br tags are kept.

**Comment by SlavaET** [comment]
Done. 
Builder will truncate all the line-breaks ( `\n`, `\r` ) from the content of Code module in BB on save.

**Comment by timayhelen** [comment]
@SlavaET This works in the BB but not the VB.

Do you think it's possible to strip the line breaks out output instead of on input, this way people can still format their code in a readable way?

**Comment by SlavaET** [comment]
@timayhelen I didn't change the behaviour in VB, because it works correctly with line-breaks. It works becuase when you save the content from VB, then WordPress doesn't perform additional processing of content and `wpautop` doesn't break the output. Do we need to make it consistent with BB and truncate the line-breaks as well?
>Do you think it's possible to strip the line breaks out output instead of on input, this way people can still format their code in a readable way?

It's possible with my original solution when we remove the `wpautop` filter, otherwise it's not possible because of `wpautop` filter. That filter is applied before we start processing the content of module. So when we process the shortcode content we cannot determine for sure whether `<p></p>`, `<p>      </p>`, `<br/>`  is just a line-break converted by wpautop or it's a code added by user on purpose.

**Comment by timayhelen** [comment]
@SlavaET I still get p and br tags added to code module content when saving in the VB, so I think we need to look into that too. 

Maybe we should look into some formatting system for Code Modules and Custom CSS text fields? This way we can strip out line breaks and then re-format the view when editing? It's something we have wanted to do anyway, to make editing code more user friendly.

**Comment by SlavaET** [comment]
@timayhelen I think I found the solution. We already have the solution for custom css option actually. In Custom css we replace the `\n` with `||` and then convert it back to `\n` when needed.
I implemented similar mechanism for the code module, but I used more complex pattern, because `||` can be added into the code by user and we'll break it. So I used the `<!-- [et_pb_line_break_holder] -->` as placeholder for line-breaks in Code module. It seems to work pretty good and should make the user experience with code module much better.
It works from any place:
1) From BB regardless of the tinyMCE mode ( text or Visual );
2) From VB in module settings;
3) From VB in the inline-editor.

> Maybe we should look into some formatting system for Code Modules and Custom CSS text fields? 

Did you mean something more complex than preserving line-breaks? 😃

**Comment by lots0logs** [comment]
@SlavaET Please see my review comments on PR. Thanks!

**Comment by SlavaET** [comment]
@lots0logs please see my reply.

**Comment by willerbee** [comment]
My code with `||` operator is being replaced with `<!-- [et_pb_line_break_holder] --> `, is there a way for divi builder to just not touch the code?

**Comment by VladET** [comment]
@willerbee The only reason why we do this is because WordPress touches it (wpautop, wptexturize, etc filters) and we are only trying to preserve the original code. The line break holder is only stored in the database and it should not output directly when editing or on the frontend. 

If you are seeing this during editing and/or on the frontend please open a chat with our support team so we can take a closer look. Thanks!

**Comment by willerbee** [comment]
i see the line break holders in when I look at the page revisions. i think it's ok. but the problem is that when I try to edit the code, the `||` operators everywhere in the code will disappear (replaced with a new line break) whenever i hover the green check save button, which breaks the script. My work around right now is to use another shortcode plugin and put shortcode in the code module instead.

**Comment by VladET** [comment]
@willerbee Do you have the latest version of Divi installed (3.19.15)? Based on your description of the problem I believe we fixed the issue in 3.19.6.

Copy from the changelog:

```
version 3.19.6 ( updated 01-18-2019 )
[...]
Fixed Code Editor replacing '||' with newlines.
[...]
```

In case you are still seeing this issue on the latest version please open a chat with our support team and include the steps to reproduce the issue if possible. I've performed some testing and it's working as expected on my end.
